#include "UniTag.h"

std::string UniTag::decodeGenre(unsigned int code)
{
    if(code ==   0) return "Blues";
    else if(code ==   1) return "Classic Rock";
    else if(code ==   2) return "Country";
    else if(code ==   3) return "Dance";
    else if(code ==   4) return "Disco";
    else if(code ==   5) return "Funk";
    else if(code ==   6) return "Grunge";
    else if(code ==   7) return "Hip-Hop";
    else if(code ==   8) return "Jazz";
    else if(code ==   9) return "Metal";
    else if(code ==  10) return "New Age";
    else if(code ==  11) return "Oldies";
    else if(code ==  12) return "Other";
    else if(code ==  13) return "Pop";
    else if(code ==  14) return "R&B";
    else if(code ==  15) return "Rap";
    else if(code ==  16) return "Reggae";
    else if(code ==  17) return "Rock";
    else if(code ==  18) return "Techno";
    else if(code ==  19) return "Industrial";
    else if(code ==  20) return "Alternative";
    else if(code ==  21) return "Ska";
    else if(code ==  22) return "Death Metal";
    else if(code ==  23) return "Pranks";
    else if(code ==  24) return "Soundtrack";
    else if(code ==  25) return "Euro-Techno";
    else if(code ==  26) return "Ambient";
    else if(code ==  27) return "Trip-Hop";
    else if(code ==  28) return "Vocal";
    else if(code ==  29) return "Jazz+Funk";
    else if(code ==  30) return "Fusion";
    else if(code ==  31) return "Trance";
    else if(code ==  32) return "Classical";
    else if(code ==  33) return "Instrumental";
    else if(code ==  34) return "Acid";
    else if(code ==  35) return "House";
    else if(code ==  36) return "Game";
    else if(code ==  37) return "Sound Clip";
    else if(code ==  38) return "Gospel";
    else if(code ==  39) return "Noise";
    else if(code ==  40) return "AlternRock";
    else if(code ==  41) return "Bass";
    else if(code ==  42) return "Soul";
    else if(code ==  43) return "Punk";
    else if(code ==  44) return "Space";
    else if(code ==  45) return "Meditative";
    else if(code ==  46) return "Instrumental Pop";
    else if(code ==  47) return "Instrumental Rock";
    else if(code ==  48) return "Ethnic";
    else if(code ==  49) return "Gothic";
    else if(code ==  50) return "Darkwave";
    else if(code ==  51) return "Techno-Industrial";
    else if(code ==  52) return "Electronic";
    else if(code ==  53) return "Pop-Folk";
    else if(code ==  54) return "Eurodance";
    else if(code ==  55) return "Dream";
    else if(code ==  56) return "Southern Rock";
    else if(code ==  57) return "Comedy";
    else if(code ==  58) return "Cult";
    else if(code ==  59) return "Gangsta";
    else if(code ==  60) return "Top 40";
    else if(code ==  61) return "Christian Rap";
    else if(code ==  62) return "Pop/Funk";
    else if(code ==  63) return "Jungle";
    else if(code ==  64) return "Native American";
    else if(code ==  65) return "Cabaret";
    else if(code ==  66) return "New Wave";
    else if(code ==  67) return "Psychadelic";
    else if(code ==  68) return "Rave";
    else if(code ==  69) return "Showtunes";
    else if(code ==  70) return "Trailer";
    else if(code ==  71) return "Lo-Fi";
    else if(code ==  72) return "Tribal";
    else if(code ==  73) return "Acid Punk";
    else if(code ==  74) return "Acid Jazz";
    else if(code ==  75) return "Polka";
    else if(code ==  76) return "Retro";
    else if(code ==  77) return "Musical";
    else if(code ==  78) return "Rock & Roll";
    else if(code ==  79) return "Hard Rock";
    else if(code ==  80) return "Folk";
    else if(code ==  81) return "Folk-Rock";
    else if(code ==  82) return "National Folk";
    else if(code ==  83) return "Swing";
    else if(code ==  84) return "Fast Fusion";
    else if(code ==  85) return "Bebob";
    else if(code ==  86) return "Latin";
    else if(code ==  87) return "Revival";
    else if(code ==  88) return "Celtic";
    else if(code ==  89) return "Bluegrass";
    else if(code ==  90) return "Avantgarde";
    else if(code ==  91) return "Gothic Rock";
    else if(code ==  92) return "Progressive Rock";
    else if(code ==  93) return "Psychedelic Rock";
    else if(code ==  94) return "Symphonic Rock";
    else if(code ==  95) return "Slow Rock";
    else if(code ==  96) return "Big Band";
    else if(code ==  97) return "Chorus";
    else if(code ==  98) return "Easy Listening";
    else if(code ==  99) return "Acoustic";
    else if(code == 100) return "Humour";
    else if(code == 101) return "Speech";
    else if(code == 102) return "Chanson";
    else if(code == 103) return "Opera";
    else if(code == 104) return "Chamber Music";
    else if(code == 105) return "Sonata";
    else if(code == 106) return "Symphony";
    else if(code == 107) return "Booty Bass";
    else if(code == 108) return "Primus";
    else if(code == 109) return "Porn Groove";
    else if(code == 110) return "Satire";
    else if(code == 111) return "Slow Jam";
    else if(code == 112) return "Club";
    else if(code == 113) return "Tango";
    else if(code == 114) return "Samba";
    else if(code == 115) return "Folklore";
    else if(code == 116) return "Ballad";
    else if(code == 117) return "Power Ballad";
    else if(code == 118) return "Rhythmic Soul";
    else if(code == 119) return "Freestyle";
    else if(code == 120) return "Duet";
    else if(code == 121) return "Punk Rock";
    else if(code == 122) return "Drum Solo";
    else if(code == 123) return "A capella";
    else if(code == 124) return "Euro-House";
    else if(code == 125) return "Dance Hall";
    return "";
}
